/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unifae.engsof.poo3.gerenciadorDeTarefas.view;
import br.unifae.engsof.poo3.gerenciadorDeTarefas.controller.TarefaController;
import br.unifae.engsof.poo3.gerenciadorDeTarefas.model.GerenciaTarefas;
import br.unifae.engsof.poo3.gerenciadorDeTarefas.model.Tarefa;
import br.unifae.engsof.poo3.gerenciadorDeTarefas.model.TarefaComPrazo;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author android
 */
public class CadastroTarefas extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTarefas
     */
    public CadastroTarefas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtdescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jformatdata = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jsliderprioridade = new javax.swing.JSlider();
        labelprazo = new javax.swing.JLabel();
        jformatprazo = new javax.swing.JFormattedTextField();
        btnCriar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableTarefas = new javax.swing.JTable();
        JRemoverIndex = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JBtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastra Tarefas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados obrigatórios"));

        jLabel1.setText("Descrição");

        jLabel2.setText("Prioridade");

        try {
            jformatdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jformatdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jformatdataActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de criação");

        jsliderprioridade.setMaximum(10);

        labelprazo.setText("Prazo");

        try {
            jformatprazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jformatprazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jformatprazoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtdescricao)
                    .addComponent(jsliderprioridade, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(jformatdata)
                    .addComponent(jformatprazo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(labelprazo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jsliderprioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jformatdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelprazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jformatprazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnCriar.setText("Criar Tarefa");
        btnCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCriarMouseClicked(evt);
            }
        });
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        JTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Descrição", "Prioridade", "Concluida", "Prazo", "Data de Criação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableTarefas);

        jLabel4.setText("Remover Tarefa");

        JBtnExcluir.setText("Excluir");
        JBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(btnCriar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JRemoverIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JBtnExcluir)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCriar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRemoverIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnExcluir))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jformatdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jformatdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jformatdataActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriarMouseClicked
        String descricao = jtxtdescricao.getText();
        int prioridade = jsliderprioridade.getValue();
        boolean error = false;
        LocalDate data = null;
        LocalDate prazo = null;
        
        if(descricao.equals("")){
            error = true;
            JOptionPane.showMessageDialog(null, "O campo descricao está vazio");
        }

        try{
            data = LocalDate.parse(jformatdata.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        }catch(Exception e){
            error = true;
            JOptionPane.showMessageDialog(null, "O campo data está vazio");
        }
        
        try{
            prazo = LocalDate.parse(jformatprazo.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        }catch(Exception e){
            prazo = null;
        }
        
        if(!error){
            boolean resp = false;
        
            if(prazo != null){
                //Adicionar uma tarefa com prazo
                resp = new TarefaController().addTarefa(descricao, prioridade, data, prazo);
            }else{
                //Adicionar uma tarefa simples
                resp = new TarefaController().addTarefa(descricao, prioridade, data);
            }

            JOptionPane.showMessageDialog(null, 
                    (resp) ? "Cadastrado" : "Erro ao cadastrar");

            if(resp){
                atualizarTabela();
                jtxtdescricao.setText("");
                jsliderprioridade.setValue(10);
                jformatdata.setText("");
                jformatprazo.setText("");
            }
        }
    }//GEN-LAST:event_btnCriarMouseClicked

    private void jformatprazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jformatprazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jformatprazoActionPerformed

    private void JBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnExcluirActionPerformed
        // TODO add your handling code here:
        int index = -1;
        try{
            index = Integer.parseInt(JRemoverIndex.getText()) - 1;
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "O valor informado nao e um numero valido");
            index = -1;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro a pergar o valor informado");
            index = -1;
        }

        try{
            int count = new TarefaController().show().size();
            if(index != -1 && count > 0){
                Tarefa tarefa = new TarefaController().index(index);
                boolean deletado = new TarefaController().remove(tarefa);
                
                if(deletado){
                    JOptionPane.showMessageDialog(null, "Tarefa excluida com sucesso");
                    atualizarTabela();
                }else{
                    JOptionPane.showMessageDialog(null, "Nao foi possivel excluir a tarefa");
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Parece que a tarefa escolhida nao existe");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar excluir a tarefa");
        }
        
    }//GEN-LAST:event_JBtnExcluirActionPerformed

    /**
     * Esta função remove todas as linhas da tabela e as coloca novamente porém com a lista de tarefas atualizada 
     */
    public void atualizarTabela(){
        //Pega o modelo para poder adicionar as linhas
        DefaultTableModel model = (DefaultTableModel) JTableTarefas.getModel();
        int countRow = model.getRowCount();
        //Remove as linhas da tabela
        for(int i = countRow-1; i>=0; i--){
            model.removeRow(i);
        }
        
        //Adciona as linhas na tabela
        List<Tarefa> lista = new TarefaController().show();
        lista.forEach((t) -> {
            String concluidaTabela = (t.isConcluida()) ? "Concluida" : "Nao concluida";
            String prazoTabela = "Nao possui prazo";
            if(t instanceof TarefaComPrazo){
                prazoTabela = ((TarefaComPrazo) t).getPrazo().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            }
            String dataCriacaoTabela = t.getDataCriacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            
            model.addRow(new Object[]{ t.getDescricao(), t.getPrioridade(), concluidaTabela, prazoTabela, dataCriacaoTabela });
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaTarefas();
                new CadastroTarefas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnExcluir;
    private javax.swing.JTextField JRemoverIndex;
    private javax.swing.JTable JTableTarefas;
    private javax.swing.JButton btnCriar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jformatdata;
    private javax.swing.JFormattedTextField jformatprazo;
    private javax.swing.JSlider jsliderprioridade;
    private javax.swing.JTextField jtxtdescricao;
    private javax.swing.JLabel labelprazo;
    // End of variables declaration//GEN-END:variables
}
